version: '2'
services:
  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
     - 35432:5432
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 575813261@qq.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 38080:80
  redis:
    image: redis:5.0.4-alpine
    ports:
      - 36379:6379
    volumes: 
      - ~/redis/data:/data
  nginx:
    image: nginx
    volumes:
     - ~/nginx/html:/usr/share/nginx/html
    ports:
     - "80:80"