version: '2'
services:
  postgres:
    image: postgres:12.0-alpine
    restart: always
    command: postgres -c 'max_connections=1024'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/pg_data/data:/var/lib/postgresql/data/pgdata
    ports:
     - 35432:5432
  redis:
    image: redis:5.0.4-alpine
    ports:
      - 36379:6379
    volumes: 
      - ~/redis/data:/data
  nginx:
    image: nginx
    volumes:
     - ~/nginx/html:/usr/share/nginx/html
    ports:
     - "80:80"