version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
       - 33306:3306
    volumes:
      - "./mysql/volume:/var/lib/mysql"
    command: mysqld -uroot --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
  redis:
    image: redis:5.0.4-alpine
    ports:
      - 36379:6379
    volumes: 
      - "./redis/data:/data"
  nginx:
    image: nginx
    volumes:
     - /Users/penghuiping/Desktop/joinsoft-docker/html:/usr/share/nginx/html
    ports:
     - "80:80"