version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.7.17-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      